services:
  web:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    ports:
      - ${APP_IP}:${WEB_PORT}:80   
    tty: true
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - ${APP_IP}:${DB_PORT}:3306  
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
